name: "GitHub Actions GasPrice Bot"

on:
  push:
  #schedule:
    # Run every 30 minutes as backup
    # - cron: "*/30 * * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
      - uses: actions/setup-python@v2
        with:
          python-version: "3.8"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Retrieve gas price data
        run: |
          # Retry 3 times
          (echo "===== Attempt: 1 ====" && python gasprice-ws.py) || \
          (echo "===== Attempt: 2 ====" && python gasprice-ws.py) || \
          (echo "===== Attempt: 3 ====" && python gasprice-ws.py) || \
          (echo "==== Crawler Failed ====" && exit 1)

      - name: Commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add ./data/
          git commit -m "Added new data by Github Action" -a

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.MY_PAT }}
          force: true
